thread_factor = 42
[proxies.ecorp]
addr = 'proxy.ecorp.com'
[proxies.allsafe]
addr = 'proxy.allsafe.com'
[links]
actions = '{{git_remote_origin}}/actions'
issues = '{{git_remote_origin}}/issues'
releases = '{{git_remote_origin}}/releases'
tags = '{{git_remote_origin}}/tags'
google = 'https://google.com'
[initializr]
from = [
    'https://github.com/beltram/initializr-rs.git',
    'https://github.com/beltram/initializr-spring.git',
]